// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Persist is an autogenerated mock type for the Persist type
type Persist struct {
	mock.Mock
}

// Getfirstfilter provides a mock function with given fields: filter
func (_m *Persist) Getfirstfilter(filter string) string {
	ret := _m.Called(filter)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(filter)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Getfulllist provides a mock function with given fields:
func (_m *Persist) Getfulllist() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
